apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-example
  name: redis-example
  namespace: default
spec:
  containers:
  - env:
    - name: REDIS_RB_CLUSTER_HOST
      value: "172.17.0.5"
    - name: REDIS_RB_CLUSTER_PORT
      value: "6379"
    image: adenda/redis-rb-cluster-docker:0.1.13
    imagePullPolicy: IfNotPresent
    name: redis-example
